---
title: "Report"
author: "Alexander Minushkin"
date: "November 28, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Results for e5-4620
--
```{r e5-4620, cache=TRUE}

usePackage <- function(p) {
  if (!is.element(p, installed.packages()[,1]))
    install.packages(p, dep = TRUE)
  require(p, character.only = TRUE, quietly=TRUE)
}

usePackage("ggplot2")
usePackage("ggforce")
usePackage("data.table")

folder = "e5-4620"

res <- data.table(read.csv(paste0("../",folder, "/results.csv"),
                           sep=" ", 
                           col.names = c("version","scale","type","run","clients","tps")))

ggplot(data = res[type=="read-only"][run==3],
       aes(x=clients, 
           y=tps, 
           group=version, 
           colour=version)) + facet_grid(scale ~ .)+
  geom_line() + geom_point() + ggtitle(paste0("pgbench ", folder, " read-only"))


ggplot(data = res[type=="read-write"][run==3],
       aes(x=clients, 
           y=tps, 
           group=version, 
           colour=version)) + facet_grid(scale ~ .)+
  geom_line() + geom_point() + ggtitle(paste0("pgbench ", folder, " read-write"))


```

Results for i5-2500k
--
```{r i5-2500k, cache=TRUE}
folder = "i5-2500k"
res <- data.table(read.csv(paste0("../",folder, "/results.csv"),
                           sep=" ", 
                           col.names = c("version","scale","type","run","clients","tps")))

ggplot(data = res[type=="read-only"][run==3],
       aes(x=clients, 
           y=tps, 
           group=version, 
           colour=version)) + facet_grid(scale ~ substr(version, 1, 1))+
  geom_line() + geom_point() + ggtitle(paste0("pgbench ", folder, " read-only"))


ggplot(data = res[type=="read-write"][run==3],
       aes(x=clients, 
           y=tps, 
           group=version, 
           colour=version)) + facet_grid(scale ~ substr(version, 1, 1))+
  geom_line() + geom_point() + ggtitle(paste0("pgbench ", folder, " read-write"))
```

